---
version: 1.0.0
name: Jekyll • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: https://jekyllrb.com
repository: https://github.com/jekyll/jekyll
logo: "/img/logo-2x.png"
collections:
  on_writing_well:
    permalink: "/books/:collection/:path/"
    book_name: "On Writing Well"
    output: true
  design_data_intensive_app:
    permalink: "/books/:collection/:path/"
    book_name: "Design Data Intensive App"
    output: true
  books:
    permalink: "/books/:path/"
    output: true
defaults:
- scope:
    path: ""
  values:
    layout: docs
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
feed:
  categories:
  - release
kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
sass:
  style: compressed
strict_front_matter: true
exclude:
- ".gitignore"
- ".jekyll-cache"
- CNAME
- icomoon-selection.json
- readme.md